
POST http://localhost:7000/api/auth/register
Content-Type: application/json

{
    "email": "thirumala1@example.com",
    "password": "thirumala123",
    "firstName": "thirumala",
    "lastName": "makkena",
    "username": "thirumalam",
    "phoneNumber":"+919392495652"
}


###
POST http://localhost:7000/api/auth/login 
Content-Type: application/json

{
    "username": "lisahall",
    "password": "lisapass456"  
}


### 

POST http://localhost:7000/api/product/add-product 
Content-Type: application/json

{ 

    "title": "Organic Apples",
    "description": "Fresh organic apples from local farms.",
    "price": 3.5,
    "quantity": 100,
    "category": "Fruits & Vegetables",
    "image": "apple-image.jpg"
}  

###

POST http://localhost:7000/api/product/add-product 
Content-Type: application/json
 
{
  "title": "Banana",
  "description": "Fresh organic bananas from local farms.",
  "price": 40,
  "quantity": 200,
  "category": "Fruits & Vegetables",
  "image": "banana-image.jpg"
}

###
POST http://localhost:7000/api/cart/add-to-cart
Content-Type: application/json

{
  "userId": "676c3dcc60c6718ea05aa7b6",
  "productId": "676d27d9ea7b55097f8fff14",
  "quantity": 10
}

###
GET http://localhost:7000/api/product/products 

###
GET http://localhost:7000/api/product/product/676c55179a4d5b1f1d9b74c6 

###
PUT http://localhost:7000/api/product/update-product/676d27d9ea7b55097f8fff14 
Content-Type: application/json

{
  "title": "Banana",
  "description": "Fresh organic bananas from local farms.",
  "price": 40,
  "quantity": 150,
  "category": "Fruits & Vegetables",
  "image": "banana-image.jpg"
}

###

GET http://localhost:7000/api/cart/get-cart-items/676c3dcc60c6718ea05aa7b6 

